{% set name = "DAWG" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34881e06278d4a54cf0b402c0c8b587bef0caa78f0eee595adc7a2aa530e48ce
  patches:
    # 2 commits from upstream PR #41 that fix build with python 3.7+
    - 41.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - dawg

about:
  home: https://github.com/pytries/DAWG
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'DAFSA-based dictionary-like read-only objects for Python'
  doc_url: http://dawg.readthedocs.io

extra:
  recipe-maintainers:
    - mcs07
