travis:
  secure:
    BINSTAR_TOKEN: fJ0tO++u0deN64BKz18M2BYsot4vebIzIu5vQ8BkfiRIUHP80JCLW5GCg6tPpbsSRCNZHY7+dBGjz+oKco0NACecGUiwM85eqenu/uvnkd0aYYESTS7QVh7AfW1GV5/6/vd7F1VZcV92NH5pGKGv4IPHfiMX7z6ABk5scL6+aJkTaOZ0ZMspdqpWDvl+5t+I7a31pZhyIyi6TdafyEZtI1yAbxMzx2h4iRJOGGTYiT/QV1U/M42TENaIh1FM5gdc4yRS4YfXMxzp+PHLgexIJaIBTSEkMlHfDThuMI2cxP38KZum++j7oYb6uLRpmZikNpAbHxj9IIq/m5zmMlgrC0SGpoB71mrENORAJ0eZQOcTIcGh9aPWXXLGlulL5ZBqYk3Uy5d72+jHmyCi3+iILCGJE7e8OG4tEvmSnrP18H3QhUCfoZB5mUK8VFp2k/A60yBRW6h3zpjxBI9pqD2B+XLkFT8iFn8gdbfCWsxRUubryDYrKOnaiLzkVbP7YLPvBZzoVrWeNGF/HNRtVgLrS5jY1DWu+81EcB1bcnL66yvf5B3Iu3DjAS5kJmEPOayzK88mSrqykVa93KMhMm7lldmxHUR55uybdPqeZVJ3oWHLsHHLtzinqPdCQ4D5kBMbbQ7Z8rRI7mqa1PguZEeUUqKo+HQwUE2Vs+REAX/lPaA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
